[Settings]
localip = 192.168.
blockfile = D:\PortableApps\Files\Programming\PYTHON-authlog\blocklist.dat
authfile = D:\PortableApps\Files\Programming\PYTHON-authlog\auth.log
failcount = 5
vncfile = D:\PortableApps\Files\Programming\PYTHON-authlog\vncserver-x11.log
restart_time = 20:24:00
autoblockusers = admin,root,pi,NL5xUDpV2xRa,ec2-user,administrator,ubuntu,webadmin,vncuser,vsftp,user,ftp,ftpuser

